# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(400, 500)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout()
		self.verticalLayout_2.setSpacing(20)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.todoView = QtWidgets.QListView(self.centralwidget)
		self.todoView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
		self.todoView.setObjectName("todoView")
		self.verticalLayout_2.addWidget(self.todoView)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setContentsMargins(40, -1, 40, -1)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
		self.deleteButton.setObjectName("deleteButton")
		self.horizontalLayout.addWidget(self.deleteButton)
		self.completeButton = QtWidgets.QPushButton(self.centralwidget)
		self.completeButton.setObjectName("completeButton")
		self.horizontalLayout.addWidget(self.completeButton)
		self.verticalLayout_2.addLayout(self.horizontalLayout)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.todoEdit = QtWidgets.QLineEdit(self.centralwidget)
		self.todoEdit.setObjectName("todoEdit")
		self.verticalLayout.addWidget(self.todoEdit)
		self.addButton = QtWidgets.QPushButton(self.centralwidget)
		self.addButton.setObjectName("addButton")
		self.verticalLayout.addWidget(self.addButton)
		self.verticalLayout_2.addLayout(self.verticalLayout)
		self.verticalLayout_3.addLayout(self.verticalLayout_2)
		MainWindow.setCentralWidget(self.centralwidget)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "Todo"))
		self.deleteButton.setText(_translate("MainWindow", "Delete"))
		self.completeButton.setText(_translate("MainWindow", "Complete"))
		self.addButton.setText(_translate("MainWindow", "Add todo"))


if __name__ == "__main__":
	import sys

	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
