# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_border_frame = QtWidgets.QFrame(Form)
        self.top_border_frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_border_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_border_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_border_frame.setObjectName("top_border_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_border_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggle_button = QtWidgets.QPushButton(self.top_border_frame)
        self.toggle_button.setMinimumSize(QtCore.QSize(0, 40))
        self.toggle_button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.toggle_button.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(170, 0, 255);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(133, 0, 200);\n"
"}")
        self.toggle_button.setFlat(True)
        self.toggle_button.setObjectName("toggle_button")
        self.horizontalLayout.addWidget(self.toggle_button)
        self.space_frame = QtWidgets.QFrame(self.top_border_frame)
        self.space_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.space_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.space_frame.setObjectName("space_frame")
        self.horizontalLayout.addWidget(self.space_frame)
        self.verticalLayout.addWidget(self.top_border_frame)
        self.bottom_frame = QtWidgets.QFrame(Form)
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_menu_frame = QtWidgets.QFrame(self.bottom_frame)
        self.left_menu_frame.setMaximumSize(QtCore.QSize(70, 16777215))
        self.left_menu_frame.setStyleSheet("background-color: rgb(67, 67, 67);")
        self.left_menu_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_frame.setObjectName("left_menu_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_menu_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.left_menu_buttons_frame = QtWidgets.QFrame(self.left_menu_frame)
        self.left_menu_buttons_frame.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(170, 0, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(133, 0, 200);\n"
"}")
        self.left_menu_buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_buttons_frame.setObjectName("left_menu_buttons_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.left_menu_buttons_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.page1_button = QtWidgets.QPushButton(self.left_menu_buttons_frame)
        self.page1_button.setMinimumSize(QtCore.QSize(70, 40))
        self.page1_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page1_button.setFlat(True)
        self.page1_button.setObjectName("page1_button")
        self.verticalLayout_4.addWidget(self.page1_button)
        self.page2_button = QtWidgets.QPushButton(self.left_menu_buttons_frame)
        self.page2_button.setMinimumSize(QtCore.QSize(70, 40))
        self.page2_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page2_button.setFlat(True)
        self.page2_button.setObjectName("page2_button")
        self.verticalLayout_4.addWidget(self.page2_button)
        self.page3_button = QtWidgets.QPushButton(self.left_menu_buttons_frame)
        self.page3_button.setMinimumSize(QtCore.QSize(70, 40))
        self.page3_button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.page3_button.setFlat(True)
        self.page3_button.setObjectName("page3_button")
        self.verticalLayout_4.addWidget(self.page3_button)
        self.verticalLayout_3.addWidget(self.left_menu_buttons_frame, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.left_menu_frame)
        self.pages_frame = QtWidgets.QFrame(self.bottom_frame)
        self.pages_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pages_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pages_frame.setObjectName("pages_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pages_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stacked_widget = QtWidgets.QStackedWidget(self.pages_frame)
        self.stacked_widget.setStyleSheet("color: rgb(255, 255, 255);")
        self.stacked_widget.setObjectName("stacked_widget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.page_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.stacked_widget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.stacked_widget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.stacked_widget.addWidget(self.page_3)
        self.verticalLayout_2.addWidget(self.stacked_widget)
        self.horizontalLayout_2.addWidget(self.pages_frame)
        self.verticalLayout.addWidget(self.bottom_frame)

        self.retranslateUi(Form)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Burguer menu"))
        self.toggle_button.setText(_translate("Form", "TOGGLE"))
        self.page1_button.setText(_translate("Form", "Page 1"))
        self.page2_button.setText(_translate("Form", "Page 2"))
        self.page3_button.setText(_translate("Form", "Page 3"))
        self.label.setText(_translate("Form", "Page 1"))
        self.label_2.setText(_translate("Form", "Page 2"))
        self.label_3.setText(_translate("Form", "Page 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
