# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 600)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        Form.setFont(font)
        Form.setStyleSheet("QWidget#Form {\n"
"    background-color: qlineargradient(spread:pad, x1:0.422726, y1:0.449, x2:1, y2:1, stop:0 rgba(56, 56, 56, 255), stop:1 rgba(103, 103, 103, 255));\n"
"}\n"
"QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(222, 222, 222);\n"
"    border: 2px solid;\n"
"    border-radius: 6px;\n"
"    border-color: rgba(0, 0, 0, 0);\n"
"    padding-left: 10px;\n"
"    padding-right: 10px\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-color: rgb(116, 116, 116)\n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: rgb(240, 240, 240);\n"
"    border-color: rgb(138, 21, 211)\n"
"}\n"
"QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 116, 228);\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(40, 138, 232);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(61, 149, 234);\n"
"}")
        self.welcome_label = QtWidgets.QLabel(Form)
        self.welcome_label.setGeometry(QtCore.QRect(135, 90, 127, 43))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.welcome_label.setFont(font)
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setObjectName("welcome_label")
        self.username_line_edit = QtWidgets.QLineEdit(Form)
        self.username_line_edit.setGeometry(QtCore.QRect(50, 217, 300, 40))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.username_line_edit.setFont(font)
        self.username_line_edit.setStyleSheet("")
        self.username_line_edit.setPlaceholderText("")
        self.username_line_edit.setObjectName("username_line_edit")
        self.password_line_edit = QtWidgets.QLineEdit(Form)
        self.password_line_edit.setGeometry(QtCore.QRect(50, 271, 300, 40))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.password_line_edit.setFont(font)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setGeometry(QtCore.QRect(62, 282, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("color: rgb(120, 120, 120)")
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.username_label = QtWidgets.QLabel(Form)
        self.username_label.setGeometry(QtCore.QRect(62, 228, 75, 17))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("color: rgb(120, 120, 120)")
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName("username_label")
        self.log_in_button = QtWidgets.QPushButton(Form)
        self.log_in_button.setGeometry(QtCore.QRect(131, 390, 137, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.log_in_button.setFont(font)
        self.log_in_button.setFlat(True)
        self.log_in_button.setObjectName("log_in_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.username_line_edit, self.password_line_edit)
        Form.setTabOrder(self.password_line_edit, self.log_in_button)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.welcome_label.setText(_translate("Form", "Welcome!"))
        self.password_label.setText(_translate("Form", "Password"))
        self.username_label.setText(_translate("Form", "Username"))
        self.log_in_button.setText(_translate("Form", "Log in"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
